export const ADD_ALL_TRACK = "ADD_TODO";
export const TOGGLE_TODO = "TOGGLE_TODO";
export const LOADING = "LOADING";
export const CURRENT_TRACK = "CURRENT_TRACK";
export const ISPLAYING_TRACK = "ISPLAYING_TRACK";
export const SHUFFLE_TRACK = "SHUFFLE_TRACK";
export const PREV_TRACK="PREV_TRACK";
export const NEXT_TRACK = "NEXT_TRACK";
/* export const NextTrack = "NextTrack";
export const PrevTrack = "PrevTrack";
export const PauseTrack = "PauseTrack"; */
